---
title: "Analysis of Demand"
author: "Mectizan Donation Program"
output:
  pdf_document: default
  word_document: default
classoption: landscape
---

```{r setup, include=FALSE}

rm(list = ls())

library("knitr")
library("markdown")
library("googlesheets")
library("Hmisc")
library("data.table")
library("rtf")
library("scales")
library("htmlTable")
library("pander")
opts_chunk$set(message=FALSE, echo = F,
               warning = F,fig.height = 5, fig.width = 10, tidy = F)

#Work
opts_knit$set(root.dir = "M:/DataManager/AnalysisOfDemand")
#Laptop

source("./aodFunctions.R")
```

```{r setvariables, include=F}
setcountry<-"Togo"
setwstitle<-"Analysis of Demand"
setwsnum<-4
setstartyr<-NA
setendyr<-NA
```

```{r function, include=FALSE}

countryX<-countryaod(setwstitle, setwsnum, setcountry, setstartyr, setendyr)

```

display original

```{r display}

kable(countryX, align=c("r"), caption=setcountry)

```

display latex

```{r }
kable(countryX, align=c("r"), format = "latex")

```

display html

```{r }

kable(countryX, align=c("r"), format = "html")

```

display rst

```{r }

kable(countryX, align=c("r"), format = "rst")

```

display markdown

```{r }

kable(countryX, align=c("r"), format = "markdown")

```

display pandoc

```{r }

kable(countryX, align=c("r"), format = "pandoc")

```

display markdown zero pad

```{r }

kable(countryX, align=c("r"), format = "markdown", padding=0)

```

display markdown 2 pad

```{r }

kable(countryX, align=c("r"), format = "markdown", padding=2)

```

end